# Generated by Django 5.1.1 on 2024-09-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_book_delete_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
